/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Janaka Ishan
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }
    
    double number1,number2,answer;
    String opr;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtanswer = new javax.swing.JTextField();
        num8 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        oparantadd = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        oparantsub = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        oparantmulti = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        num00 = new javax.swing.JButton();
        numpoint = new javax.swing.JButton();
        oparantdivi = new javax.swing.JButton();
        oparantdivi1 = new javax.swing.JButton();
        num10 = new javax.swing.JButton();
        num11 = new javax.swing.JButton();
        numpoint1 = new javax.swing.JButton();
        oparantdivi2 = new javax.swing.JButton();
        num12 = new javax.swing.JButton();
        num13 = new javax.swing.JButton();
        numpoint2 = new javax.swing.JButton();
        num14 = new javax.swing.JButton();
        numpoint3 = new javax.swing.JButton();
        num15 = new javax.swing.JButton();
        numpoint4 = new javax.swing.JButton();
        numpoint5 = new javax.swing.JButton();
        numpoint6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Calculator");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtanswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtanswer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtanswer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtanswer.setPreferredSize(new java.awt.Dimension(75, 31));
        txtanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanswerActionPerformed(evt);
            }
        });

        num8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num8.setText("8");
        num8.setPreferredSize(new java.awt.Dimension(60, 40));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num7.setText("9");
        num7.setPreferredSize(new java.awt.Dimension(60, 40));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num9.setText("7");
        num9.setPreferredSize(new java.awt.Dimension(60, 40));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        oparantadd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oparantadd.setText("+");
        oparantadd.setPreferredSize(new java.awt.Dimension(60, 40));
        oparantadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oparantaddActionPerformed(evt);
            }
        });

        num5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num5.setText("5");
        num5.setPreferredSize(new java.awt.Dimension(60, 40));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num6.setText("6");
        num6.setPreferredSize(new java.awt.Dimension(60, 40));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num4.setText("4");
        num4.setPreferredSize(new java.awt.Dimension(60, 40));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        oparantsub.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oparantsub.setText("-");
        oparantsub.setPreferredSize(new java.awt.Dimension(60, 40));
        oparantsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oparantsubActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num2.setText("2");
        num2.setPreferredSize(new java.awt.Dimension(60, 40));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num3.setText("3");
        num3.setPreferredSize(new java.awt.Dimension(60, 40));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num1.setText("1");
        num1.setPreferredSize(new java.awt.Dimension(60, 40));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        oparantmulti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oparantmulti.setText("*");
        oparantmulti.setPreferredSize(new java.awt.Dimension(60, 40));
        oparantmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oparantmultiActionPerformed(evt);
            }
        });

        num0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num0.setText("0");
        num0.setPreferredSize(new java.awt.Dimension(60, 40));
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        num00.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num00.setText("00");
        num00.setPreferredSize(new java.awt.Dimension(60, 40));
        num00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num00ActionPerformed(evt);
            }
        });

        numpoint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numpoint.setText(".");
        numpoint.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpointActionPerformed(evt);
            }
        });

        oparantdivi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oparantdivi.setText("/");
        oparantdivi.setPreferredSize(new java.awt.Dimension(60, 40));
        oparantdivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oparantdiviActionPerformed(evt);
            }
        });

        oparantdivi1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oparantdivi1.setText("%");
        oparantdivi1.setPreferredSize(new java.awt.Dimension(60, 40));
        oparantdivi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oparantdivi1ActionPerformed(evt);
            }
        });

        num10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num10.setText("X^2");
        num10.setPreferredSize(new java.awt.Dimension(60, 40));
        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });

        num11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num11.setText("1/X");
        num11.setPreferredSize(new java.awt.Dimension(60, 40));
        num11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num11ActionPerformed(evt);
            }
        });

        numpoint1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpoint1.setText("X^3");
        numpoint1.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpoint1ActionPerformed(evt);
            }
        });

        oparantdivi2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oparantdivi2.setText("=");
        oparantdivi2.setPreferredSize(new java.awt.Dimension(60, 40));
        oparantdivi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oparantdivi2ActionPerformed(evt);
            }
        });

        num12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num12.setText("n!");
        num12.setPreferredSize(new java.awt.Dimension(60, 40));
        num12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num12ActionPerformed(evt);
            }
        });

        num13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        num13.setText("Clear");
        num13.setPreferredSize(new java.awt.Dimension(60, 40));
        num13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num13ActionPerformed(evt);
            }
        });

        numpoint2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpoint2.setText("X^7");
        numpoint2.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpoint2ActionPerformed(evt);
            }
        });

        num14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num14.setText("X^6");
        num14.setPreferredSize(new java.awt.Dimension(60, 40));
        num14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num14ActionPerformed(evt);
            }
        });

        numpoint3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpoint3.setText("X^8");
        numpoint3.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpoint3ActionPerformed(evt);
            }
        });

        num15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num15.setText("X^5");
        num15.setPreferredSize(new java.awt.Dimension(60, 40));
        num15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num15ActionPerformed(evt);
            }
        });

        numpoint4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpoint4.setText("X^4");
        numpoint4.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpoint4ActionPerformed(evt);
            }
        });

        numpoint5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        numpoint5.setText("SR");
        numpoint5.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpoint5ActionPerformed(evt);
            }
        });

        numpoint6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpoint6.setText("X^9");
        numpoint6.setPreferredSize(new java.awt.Dimension(60, 40));
        numpoint6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpoint6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numpoint2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numpoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numpoint4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numpoint5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numpoint3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numpoint6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oparantsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oparantadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oparantmulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oparantdivi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oparantdivi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oparantdivi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oparantadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oparantsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oparantmulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oparantdivi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(oparantdivi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numpoint4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numpoint3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numpoint2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numpoint6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(oparantdivi2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpoint5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "7");
    }//GEN-LAST:event_num9ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "4");
    }//GEN-LAST:event_num4ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "1");
    }//GEN-LAST:event_num1ActionPerformed

    private void numpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpointActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + ".");
    }//GEN-LAST:event_numpointActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "3");
    }//GEN-LAST:event_num3ActionPerformed

    private void numpoint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpoint1ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_numpoint1ActionPerformed

    private void num11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num11ActionPerformed
        // TODO add your handling code here:
         double t=Double.parseDouble(txtanswer.getText());
        
        t=1/t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_num11ActionPerformed

    private void oparantdivi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oparantdivi1ActionPerformed
        // TODO add your handling code here:
        number1 = Double.parseDouble(txtanswer.getText());
        
        txtanswer.setText("");
        
        opr = "%";
    }//GEN-LAST:event_oparantdivi1ActionPerformed

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
        
    }//GEN-LAST:event_num10ActionPerformed

    private void oparantdivi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oparantdivi2ActionPerformed
        // TODO add your handling code here:
        number2 = Double.parseDouble(txtanswer.getText());
        
        if(opr == "+"){
            
            answer=number1+number2;
            txtanswer.setText(Double.toString(answer));
        }
        else if (opr == "-") {
               
            answer=number1-number2;
            txtanswer.setText(Double.toString(answer));
          }
          
        else if (opr == "*") {
               
            answer=number1*number2;
            txtanswer.setText(Double.toString(answer));
          }
        
         else if (opr == "/") {
               
            answer=number1/number2;
            txtanswer.setText(Double.toString(answer));
          }
        
         else if (opr == "%") {
               
            answer=number1%number2;
            txtanswer.setText(Double.toString(answer));
          }
        
         else if(opr == "x^y"){
        
            
        double answer=1;
        for(int i=0;i<number2;i++){
            answer=number1*number2;
        }
        
        txtanswer.setText(Double.toString(answer));
    }
        
        
        
        
        

    }//GEN-LAST:event_oparantdivi2ActionPerformed

    private void num12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num12ActionPerformed

    private void num13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num13ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText("");
    }//GEN-LAST:event_num13ActionPerformed

    private void numpoint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpoint2ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t*t*t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_numpoint2ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "0");
    }//GEN-LAST:event_num0ActionPerformed

    private void num00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num00ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "00");
    }//GEN-LAST:event_num00ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "2");
    }//GEN-LAST:event_num2ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "5");
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "6");
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "9");
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        txtanswer.setText(txtanswer.getText() + "8");
    }//GEN-LAST:event_num8ActionPerformed

    private void oparantaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oparantaddActionPerformed
        // TODO add your handling code here:
        
        number1 = Double.parseDouble(txtanswer.getText());
        
        txtanswer.setText("");
        
        opr = "+";
    }//GEN-LAST:event_oparantaddActionPerformed

    private void oparantsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oparantsubActionPerformed
        // TODO add your handling code here:
        number1 = Double.parseDouble(txtanswer.getText());
        
        txtanswer.setText("");
        
        opr = "-";
    }//GEN-LAST:event_oparantsubActionPerformed

    private void oparantmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oparantmultiActionPerformed
        // TODO add your handling code here:
        number1 = Double.parseDouble(txtanswer.getText());
        
        txtanswer.setText("");
        
        opr = "*";
    }//GEN-LAST:event_oparantmultiActionPerformed

    private void oparantdiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oparantdiviActionPerformed
        // TODO add your handling code here:
        number1 = Double.parseDouble(txtanswer.getText());
        
        txtanswer.setText("");
        
        opr = "/";
    }//GEN-LAST:event_oparantdiviActionPerformed

    private void num14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num14ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t*t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_num14ActionPerformed

    private void numpoint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpoint3ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t*t*t*t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_numpoint3ActionPerformed

    private void num15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num15ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_num15ActionPerformed

    private void numpoint4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpoint4ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_numpoint4ActionPerformed

    private void numpoint5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpoint5ActionPerformed
        // TODO add your handling code here:
        double t = Double.parseDouble(txtanswer.getText());
    
    t = Math.sqrt(t);
    txtanswer.setText(Double.toString(t));
    }//GEN-LAST:event_numpoint5ActionPerformed

    private void numpoint6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpoint6ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(txtanswer.getText());
        
        t=t*t*t*t*t*t*t*t*t;
        txtanswer.setText("");
        txtanswer.setText(txtanswer.getText()+t);
    }//GEN-LAST:event_numpoint6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton num0;
    private javax.swing.JButton num00;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num11;
    private javax.swing.JButton num12;
    private javax.swing.JButton num13;
    private javax.swing.JButton num14;
    private javax.swing.JButton num15;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton numpoint;
    private javax.swing.JButton numpoint1;
    private javax.swing.JButton numpoint2;
    private javax.swing.JButton numpoint3;
    private javax.swing.JButton numpoint4;
    private javax.swing.JButton numpoint5;
    private javax.swing.JButton numpoint6;
    private javax.swing.JButton oparantadd;
    private javax.swing.JButton oparantdivi;
    private javax.swing.JButton oparantdivi1;
    private javax.swing.JButton oparantdivi2;
    private javax.swing.JButton oparantmulti;
    private javax.swing.JButton oparantsub;
    private javax.swing.JTextField txtanswer;
    // End of variables declaration//GEN-END:variables
}
